version: '3.3.1-{build}'

init:
- ps: |
    $version = $env:APPVEYOR_BUILD_VERSION.Split('-')[0]
    $date = Get-Date -Format "yyyyMMdd"
    Update-AppveyorBuild -Version "$version.$date-beta-$env:APPVEYOR_BUILD_NUMBER"
    Write-Host $env:APPVEYOR_BUILD_VERSION
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

image: Visual Studio 2017

before_build:
- git submodule update --init --recursive
- nuget restore
- dotnet restore

configuration: Release
platform:
- x86
- x64
build:
  project: OpenCvSharp.sln
  parallel: true
  verbosity: minimal


after_build:
- ps: |
    (ls $env:APPVEYOR_BUILD_FOLDER -Recurse).Where{ $_.Extension -eq ".nuspec" }.ForEach{
      [xml]$xml = Get-Content $_.FullName
      $xml.package.metadata.version = $env:APPVEYOR_BUILD_VERSION
      $xml.Save($_.FullName)
    }
    nuget pack nuget/OpenCvSharp3-AnyCPU.nuspec -OutputDirectory artifacts
    nuget pack nuget/OpenCvSharp3-WithoutDll.nuspec -OutputDirectory artifacts

test_script:
#- nunit3-console.exe ./test/OpenCvSharp.Tests/bin/Release/net461/OpenCvSharp.Tests.dll --result=myresults.xml;format=AppVeyor
# https://www.appveyor.com/docs/running-tests/#nunit-3x
#- xunit.console ./test/OpenCvSharp.Tests/bin/Release/net461/OpenCvSharp.Tests.dll /appveyor
- dotnet test ./test/OpenCvSharp.Tests/OpenCvSharp.Tests.csproj --no-build


artifacts:
- path: artifacts\**\*.*

deploy:
- provider: NuGet # appveyor
  server: https://ci.appveyor.com/nuget/shimat
  api_key:
    secure: PW0F7tbGr+QLuLPUGy+32pNtMZUJeqjyikz9nKlpALA=
  skip_symbols: true
  artifact: /.*\.nupkg/
- provider: NuGet # nuget.org
  api_key:
    secure: qea/3lnas374qyS4Xw9t5Z5jBKsVsBPGsY938QHgJ2IQyrQmug0qPKDU7tll/QkJ
  skip_symbols: true
  artifact: /.*\.nupkg/
