version: '3.3.1-{build}'

init:
- ps: |
    $version = $env:APPVEYOR_BUILD_VERSION.Split('-')[0]
    $date = Get-Date -Format "yyyyMMdd"
    Update-AppveyorBuild -Version "$version.$date-beta-$env:APPVEYOR_BUILD_NUMBER"
    Write-Host $env:APPVEYOR_BUILD_VERSION
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    Write-Host $env:APPVEYOR
    Write-Host $env:CI
    Write-Host $env:APPVEYOR_API_URL
    Write-Host $env:APPVEYOR_ACCOUNT_NAME
    Write-Host $env:APPVEYOR_PROJECT_ID
    Write-Host $env:APPVEYOR_PROJECT_NAME
    Write-Host $env:APPVEYOR_PROJECT_SLUG
    Write-Host $env:APPVEYOR_BUILD_FOLDER
    Write-Host $env:APPVEYOR_BUILD_ID
    Write-Host $env:APPVEYOR_BUILD_NUMBER
    Write-Host $env:APPVEYOR_BUILD_VERSION
    Write-Host $env:APPVEYOR_BUILD_WORKER_IMAGE
    Write-Host $env:APPVEYOR_PULL_REQUEST_NUMBER
    Write-Host $env:APPVEYOR_PULL_REQUEST_TITLE
    Write-Host $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME
    Write-Host $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH
    Write-Host $env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT
    Write-Host $env:APPVEYOR_JOB_ID
    Write-Host $env:APPVEYOR_JOB_NAME
    Write-Host $env:APPVEYOR_JOB_NUMBER
    Write-Host $env:APPVEYOR_REPO_PROVIDER
    Write-Host $env:APPVEYOR_REPO_SCM
    Write-Host $env:APPVEYOR_REPO_NAME
    Write-Host $env:APPVEYOR_REPO_BRANCH
    Write-Host $env:APPVEYOR_REPO_TAG
    Write-Host $env:APPVEYOR_REPO_TAG_NAME
    Write-Host $env:APPVEYOR_REPO_COMMIT
    Write-Host $env:APPVEYOR_REPO_COMMIT_AUTHOR
    Write-Host $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
    Write-Host $env:APPVEYOR_REPO_COMMIT_TIMESTAMP
    Write-Host $env:APPVEYOR_REPO_COMMIT_MESSAGE
    Write-Host $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED
    Write-Host $env:APPVEYOR_SCHEDULED_BUILD
    Write-Host $env:PLATFORM
    Write-Host $env:CONFIGURATION

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

image: Visual Studio 2017

configuration: Release

before_build:
#- git submodule update --init --recursive
- git submodule update --init
- ps: |
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    function Unzip {
        param([string]$zipfile, [string]$outpath)
        $pwd = pwd
        $zipfile = [System.IO.Path]::Combine($pwd, $zipfile)
        $outpath = [System.IO.Path]::Combine($pwd, $outpath)
        [System.IO.Compression.ZipFile]::ExtractToDirectory($zipfile, $outpath)
    }
    Unzip tesseract\build\v141\x86.zip tesseract\build\v141
    Unzip tesseract\build\v141\x64.zip tesseract\build\v141
- nuget restore
- dotnet restore

build_script:
- msbuild OpenCvSharp.sln /t:build /p:configuration=%CONFIGURATION% /p:platform=x64
- msbuild OpenCvSharp.sln /t:build /p:configuration=%CONFIGURATION% /p:platform=x86

after_build:
- ps: |
    (ls $env:APPVEYOR_BUILD_FOLDER -Recurse).Where{ $_.Extension -eq ".nuspec" }.ForEach{
      [xml]$xml = Get-Content $_.FullName
      $xml.package.metadata.version = $env:APPVEYOR_BUILD_VERSION
      $xml.Save($_.FullName)
    }
    nuget pack nuget/OpenCvSharp3-AnyCPU.nuspec -OutputDirectory artifacts
    nuget pack nuget/OpenCvSharp3-WithoutDll.nuspec -OutputDirectory artifacts

test_script:
#- nunit3-console.exe ./test/OpenCvSharp.Tests/bin/Release/net461/OpenCvSharp.Tests.dll --result=myresults.xml;format=AppVeyor
# https://www.appveyor.com/docs/running-tests/#nunit-3x
#- xunit.console ./test/OpenCvSharp.Tests/bin/Release/net461/OpenCvSharp.Tests.dll /appveyor
- dotnet test ./test/OpenCvSharp.Tests/OpenCvSharp.Tests.csproj --no-build


artifacts:
- path: artifacts\**\*.*

deploy:
- provider: NuGet # appveyor
  server: https://ci.appveyor.com/nuget/shimat
  api_key:
    secure: PW0F7tbGr+QLuLPUGy+32pNtMZUJeqjyikz9nKlpALA=
  skip_symbols: true
  artifact: /.*\.nupkg/
#- provider: NuGet # nuget.org
#  api_key:
#    secure: qea/3lnas374qyS4Xw9t5Z5jBKsVsBPGsY938QHgJ2IQyrQmug0qPKDU7tll/QkJ
#  skip_symbols: true
#  artifact: /.*\.nupkg/
